config/routes.rb
Ncaa::Application.routes.draw do
  get "charges/increase_pool_size"
  post "charges/pay_for_increase" => "charges#pay_for_increase", as: :charges_pay_for_increase
  get "cutoff_date/edit" => "cutoff_date#edit", as: :cutoff_date_edit
  put "cutoff_date/update" => "cutoff_date#update", as: :cutoff_date_update
  put "brackets/update_master" => "brackets#update_master", as: :brackets_update_master
  get "accountsettings/show"
  get "accountsettings/group_welcome"
  get "standings/show"
  get "teams/edit" => "teams#edit", as: :teams_edit
  put "teams/update" => "teams#update", as: :teams_update
  get "brackets/edit" => "brackets#edit", as: :brackets_edit
  get "brackets/:user_id/view" => "brackets#view", as: :brackets_view
  get "brackets/edit_master" => "brackets#edit_master", as: :edit_master_bracket
  get "brackets/view_master" => "brackets#view_master", as: :view_master_bracket
	resources :brackets
	resources :charges
  devise_for :admins, :controllers => { :registrations => :registrations }
  devise_for :players, :controllers => { :registrations => :registrations }
  get "staticpages/index"
  get "howitworks" => "staticpages#howitworks", as: :staticpages_howitworks
  get "scoring" => "staticpages#scoring", as: :staticpages_scoring
  get "pricing" => "staticpages#pricing", as: :staticpages_pricing
  get "contact" => "staticpages#contact", as: :staticpages_contact
  get "staticpages/notauthorized"
  get "staticpages/nopairings"
  get "staticpages/signupthanks"
  get "staticpages/notpaid"
  get "staticpages/overmaxplayers"
  get "staticpages/nomoresignups"

  get "testpages/test"

  root 'staticpages#index'

  

end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
  def index
  end
  def pricing
  end
  def scoring
  end
  def howitworks
  end
  def notauthorized
  end
  def signupthanks
  end
  def notpaid
  end
  def overmaxplayers
  end
  def nomoresignups
  end
  def contact
  end
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
   def get_admin
      if (player_signed_in?)
        user = current_player
      elsif (admin_signed_in?)
        user = current_admin
      end

      admin = Player.where("upper(pool_name) = upper(?) and is_admin = 1", user.pool_name)
			return admin[0]
    end
end

app/views/staticpages/contact.html.erb
<%content_for :title do%>Contact<%end%>
<h1>Contact</h1>
<br>
<p>
	Send us an email at <a href="mailto:support@.playoffpoolz.com">support@playoffpoolz.com</a>	
</p>

app/views/staticpages/howitworks.html.erb
<%content_for :title do%>How It Works<%end%>
<h1>How It Works</h1>
<br>
<ul id="how_it_works_list" class="list-group">
	<li class="list-group-item">
		<h4 class="list-group-item-heading hiw_list_heading">Create a pool</h4>
		Sign up and create your own NBA playoff pool.  During sign up you will be asked to pick a unique pool name.  This name will be used to identify your pool from others.  It is what your friends will use when they sign up.
	</li>
	<li class="list-group-item">
		<h4 class="list-group-item-heading hiw_list_heading">Invite your friends</h4>
		Let your friends, family, co-workers, etc know to sign up for your NBA playoff pool.  Give them the pool name you chose when you created the pool.  They need to use the pool name when they sign up.
	</li>
	<li class="list-group-item">
		<h4 class="list-group-item-heading hiw_list_heading">Make your picks</h4>
		Upon sign in, you will be taken directly to your personal NBA playoff bracket.  If the pairings are out, you can make your picks and save your bracket. The same applies to all players in your pool.
	</li>
	<li class="list-group-item">
		<h4 class="list-group-item-heading hiw_list_heading">Check the pool standings</h4>
		Once the NBA playoffs begin, standings and bracket results will be updated after every series.  Check in frequently to see how you are doing against others in your playoff pool. 
	</li>
	<li class="list-group-item">
		<h4 class="list-group-item-heading hiw_list_heading">Crown the winner!</h4>
		After the NBA playoffs are complete check the point standings to determine the winner.  Shower them with glory and praise.
	</li>
</ul>
<br>
  <p>
	<div>
		<a class="btn btn-primary btn-lg" href="/admins/sign_up" role="button" >Create your own NBA playoff pool</a>
	</div>
	</p>

app/views/staticpages/index.html.erb
<h1> Create an NBA playoff pool. </h1>
<h2>Invite your friends, co-workers and enemies.</h2>
<h2>Humiliate them with your outstanding basketball prowess.</h2>
<h2>Bask in the glory for a year.</h2>
<br>
  <p>
	<div>
		<a class="btn btn-primary btn-lg" href="/admins/sign_up" role="button" >Create your own NBA playoff pool</a>
	</div>
	</p>

app/views/staticpages/nomoresignups.html.erb
<h2>
				Your request to register was sent to the 
				<span class="glyphicon glyphicon-trash"></span>
				because the date to sign up for your pool has gone and went.  Sorry :(
</h2>

app/views/staticpages/nopairings.html.erb
<h2>
			This page will be available as soon as the tournament pairings are out.	
</h2>

app/views/staticpages/notauthorized.html.erb
<h2>
				Your request was sent to the
				<span class="glyphicon glyphicon-trash"></span>
				because you are not authorized to view that page.
</h2>

app/views/staticpages/notpaid.html.erb
<h2>
				Your request was sent to the
				<span class="glyphicon glyphicon-trash"></span>
				because your tournament pool has not been paid for.
</h2>

<% a = get_admin %>

<h4>
				Tell <%= a.first_name %> <%= a.last_name %> (<%=a.email%>) to login and pay the bill!
</h4>
<h4>
				Or you can pay the bill for your pool, click <%= link_to "here", new_charge_path %> to pay.
</h4>

app/views/staticpages/overmaxplayers.html.erb
<h2>
				Your request to register was sent to the 
				<span class="glyphicon glyphicon-trash"></span>
				because your tournament pool has reached the maximum number of players.
</h2>

app/views/staticpages/pricing.html.erb
<%content_for :title do%>Pricing<%end%>
<h1>Pricing</h1>
<br>
<ul id="pricing_list" class="list-group">
	<li class="list-group-item">
		Pool Size
		<ul>
			<li>Up to 15 players... $20</li>
			<li>Up to 35 players... $35</li>
			<li>Up to 65 players... $50</li>
			<li>Up to 100 players... $75</li>
		</ul>
	</li>
	<li class="list-group-item">
		Pay a one-time fee when you create an NBA playoff  pool.  
	</li>
	<li class="list-group-item">
		When co-workers, family and friends sign up for your pool it's free for them.
	</li>
	<li class="list-group-item">
		If you are less than pleased with the product for <b>ANY</b> reason, you will be refunded your payment amount in full.
	</li>
</ul>
<br>
  <p>
	<div>
		<a class="btn btn-primary btn-lg" href="/admins/sign_up" role="button" >Create your own NBA playoff pool</a>
	</div>
	</p>

app/views/staticpages/scoring.html.erb
<%content_for :title do%>Scoring<%end%>
<h1>Scoring</h1>
<br>
<ul id="scoring_list" class="list-group">
	<li class="list-group-item">Scoring is awarded by round.  A correct pick in each round is awarded the following point(s).</li>
	<li class="list-group-item">Round 1 <span class="badge points_badge">1 point</span></li>
	<li class="list-group-item">Round 2 <span class="badge points_badge">2 points</span></li>
	<li class="list-group-item">Round 3 <span class="badge points_badge">4 points</span></li>
	<li class="list-group-item">Round 4 <span class="badge points_badge">6 points</span></li>
</ul>
<h2>Pick a perfect bracket and earn 30 points.  Good Luck!</h2>
	<br>
  <p>
	<div>
		<a class="btn btn-primary btn-lg" href="/admins/sign_up" role="button" >Create your own NCAA tournament pool</a>
	</div>
	</p>

app/views/staticpages/signupthanks.html.erb
<h1>Signup Complete</h1>
<h2>Invite others to join your pool.</h2>
<h2>Send them this link:  <%= link_to new_player_registration_url, new_player_registration_path %></h2>
<% if admin_signed_in? %>
	<h2>Have them to sign up using your pool name: <%= current_admin.pool_name.titleize %> </h2>
<% end %>
<% if player_signed_in? %>
	<h2>Have them to sign up using your pool name: <%= current_player.pool_name.titleize %> </h2>
<% end %>
<br>
<h2>Get started filling out your <%= link_to "bracket", brackets_edit_path %></h2>