config/routes.rb
Ncaa::Application.routes.draw do
  get "charges/increase_pool_size"
  post "charges/pay_for_increase" => "charges#pay_for_increase", as: :charges_pay_for_increase
  get "cutoff_date/edit" => "cutoff_date#edit", as: :cutoff_date_edit
  put "cutoff_date/update" => "cutoff_date#update", as: :cutoff_date_update
  put "brackets/update_master" => "brackets#update_master", as: :brackets_update_master
  get "accountsettings/show"
  get "accountsettings/group_welcome"
  get "standings/show"
  get "teams/edit" => "teams#edit", as: :teams_edit
  put "teams/update" => "teams#update", as: :teams_update
  get "brackets/edit" => "brackets#edit", as: :brackets_edit
  get "brackets/:user_id/view" => "brackets#view", as: :brackets_view
  get "brackets/edit_master" => "brackets#edit_master", as: :edit_master_bracket
  get "brackets/view_master" => "brackets#view_master", as: :view_master_bracket
	resources :brackets
	resources :charges
  devise_for :admins, :controllers => { :registrations => :registrations }
  devise_for :players, :controllers => { :registrations => :registrations }
  get "staticpages/index"
  get "howitworks" => "staticpages#howitworks", as: :staticpages_howitworks
  get "scoring" => "staticpages#scoring", as: :staticpages_scoring
  get "pricing" => "staticpages#pricing", as: :staticpages_pricing
  get "contact" => "staticpages#contact", as: :staticpages_contact
  get "staticpages/notauthorized"
  get "staticpages/nopairings"
  get "staticpages/signupthanks"
  get "staticpages/notpaid"
  get "staticpages/overmaxplayers"
  get "staticpages/nomoresignups"

  get "testpages/test"

  root 'staticpages#index'

  

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
before_filter :check_for_login

def new
end

def create
  customer = Stripe::Customer.create(
    :email => 'example@stripe.com',
    :card  => params[:stripeToken]
  )

  charge = Stripe::Charge.create(
    :customer    => customer.id,
    :amount      => params[:charge_amt],
    :description => 'Rails Stripe customer',
    :currency    => 'usd'
  )


    if (player_signed_in?)
      user = Player.find(current_player.id)
    elsif (admin_signed_in?)
      user = Admin.find(current_admin.id)
    end
		
		user.is_paid = 1
		user.player_limit = params[:player_limit]
		user.save

		# Edge case where Admin created a pool but didn't pay.  Then a player signed up, got the
		# "pool hasn't been paid for" message and paid.  Need to mark the admin account as paid
		# to indicate the pool has been paid for.
		if (user.is_admin != 1)	
			a = get_admin
			a.is_paid = 1
			a.player_limit = params[:player_limit]
			a.save
		end

    redirect_to staticpages_signupthanks_path

	rescue Stripe::CardError => e
  	flash[:error] = e.message
  	redirect_to charges_path

end

def pay_for_increase
  customer = Stripe::Customer.create(
    :email => params[:stripeEmail],
    :card  => params[:stripeToken]
  )

  charge = Stripe::Charge.create(
    :customer    => customer.id,
    :amount      => params[:charge_amt],
    :description => 'Increasing player limit on pool',
    :currency    => 'usd'
  )


    if (player_signed_in?)
      user = Player.find(current_player.id)
    elsif (admin_signed_in?)
      user = Admin.find(current_admin.id)
    end

		# If a user paid for an increase, just mark it as paid and record
		# the number of players he/she increased the pool by.
    user.is_paid = 1
		if user.player_limit.blank?
    	user.player_limit = params[:player_addition]
		else
    	user.player_limit = user.player_limit + params[:player_addition].to_i
		end
    user.save

    # Increase the player_limit on the admin record for this pool.
    if (user.is_admin != 1)
      a = get_admin
      a.is_paid = 1
      a.player_limit = a.player_limit + params[:player_addition].to_i
      a.save
    end

    redirect_to charges_increase_pool_size_path

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to charges_path

end


def increase_pool_size
    if (player_signed_in?)
      a = get_admin
			@pool_name = current_player.pool_name
			@max_pool_size = a.player_limit
    elsif (admin_signed_in?)
			@max_pool_size = current_admin.player_limit
			@pool_name = current_admin.pool_name
    end
		@current_pool_size = get_current_pool_size @pool_name
end

	private

   def check_for_login
      redirect_to staticpages_index_path unless (player_signed_in? || admin_signed_in?)
   end

   def get_admin
      if (player_signed_in?)
        user = current_player
      elsif (admin_signed_in?)
        user = current_admin
      end

      admin = Player.where("upper(pool_name) = upper(?) and is_admin = 1", user.pool_name)
      return admin[0]
    end

   def get_current_pool_size (pool_name)
      players = Player.where("upper(pool_name) = upper(?)", pool_name)
      return players.count
    end

end

app/helpers/charges_helper.rb
module ChargesHelper

  def get_email()
		if (player_signed_in?)
      return current_player.email
    else
    	return current_admin.email  
    end
  end


end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/increase_pool_size.html.erb
<h1><%=@pool_name.titleize%> Pool Information</h1>
<h3>Maximum pool size: <%= @max_pool_size %></h3>
<h3>Number of players currently signed up: <%= @current_pool_size %></h3>
<br>

<ul class="list-group">

<li class="list-group-item">
<%= form_tag charges_pay_for_increase_path do %>
<%= hidden_field_tag(:charge_amt, "1000") %>
<%= hidden_field_tag(:player_addition, "10") %>
<span class="choose_num_players_text">Add 10 more players...  </span>
<div class="float_right">
  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="NCAA tourney pool add 10 players"
          data-email=<%= get_email %>
					data-allow-remember-me="false"
          data-name="NCAA Tourney Pool"
          data-label="Pay $10.00"
          data-amount="1000"></script>
</div>
<div class="clear_right">
</div>
<% end %>
</li>

<li class="list-group-item">
<%= form_tag charges_pay_for_increase_path do %>
<%= hidden_field_tag(:charge_amt, "2000") %>
<%= hidden_field_tag(:player_addition, "20") %>
<span class="choose_num_players_text">Add 20 more players...  </span>
<div class="float_right">
  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="NCAA tourney pool add 20 players"
          data-email=<%= get_email %>
					data-allow-remember-me="false"
          data-name="NCAA Tourney Pool"
          data-label="Pay $20.00"
          data-amount="2000"></script>
</div>
<div class="clear_right">
</div>
<% end %>
</li>

<li class="list-group-item">
<%= form_tag charges_pay_for_increase_path do %>
<%= hidden_field_tag(:charge_amt, "3000") %>
<%= hidden_field_tag(:player_addition, "30") %>
<span class="choose_num_players_text">Add 30 more players...  </span>
<div class="float_right">
  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="NCAA tourney pool add 30 players"
          data-email=<%= get_email %>
					data-allow-remember-me="false"
          data-name="NCAA Tourney Pool"
          data-label="Pay $30.00"
          data-amount="3000"></script>
</div>
<div class="clear_right">
</div>
<% end %>
</li>


</ul>

app/views/charges/new.html.erb
<h2>Choose the Number of Players in your Pool.</h2>

<ul class="list-group">

<li class="list-group-item">
<%= form_tag charges_path do %>
<%= hidden_field_tag(:charge_amt, "2000") %>
<%= hidden_field_tag(:player_limit, "15") %>
<span class="choose_num_players_text">Up to 15 Players...  </span>
<div class="float_right">
  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="NBA tourney pool 15 players"
          data-email=<%= get_email %>
					data-allow-remember-me="false"
          data-name="NBA Tourney Pool"
          data-label="Pay $20.00"
          data-amount="2000"></script>
</div>
<div class="clear_right">
</div>
<% end %>
</li>

<li class="list-group-item">
<%= form_tag charges_path do %>
<%= hidden_field_tag(:charge_amt, "3500") %>
<%= hidden_field_tag(:player_limit, "35") %>
<span class="choose_num_players_text">Up to 35 Players...  </span>
<div class="float_right">
  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="NBA tourney pool 35 players"
          data-email=<%= get_email %>
					data-allow-remember-me="false"
          data-name="NBA Tourney Pool"
          data-label="Pay $35.00"
          data-amount="3500"></script>
</div>
<div class="clear_right">
</div>
<% end %>
</li>

<li class="list-group-item">
<%= form_tag charges_path do %>
<%= hidden_field_tag(:charge_amt, "5000") %>
<%= hidden_field_tag(:player_limit, "65") %>
<span class="choose_num_players_text">Up to 65 Players...  </span>
<div class="float_right">
  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="NBA tourney pool 65 players"
          data-email=<%= get_email %>
					data-allow-remember-me="false"
          data-name="NBA Tourney Pool"
          data-label="Pay $50.00"
          data-amount="5000"></script>
</div>
<div class="clear_right">
</div>
<% end %>
</li>

<li class="list-group-item">
<%= form_tag charges_path do %>
<%= hidden_field_tag(:charge_amt, "7500") %>
<%= hidden_field_tag(:player_limit, "100") %>
<span class="choose_num_players_text">Up to 100 Players</span> (You don't have this many friends!)
<div class="float_right">
  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="NBA tourney pool 100 players"
          data-email=<%= get_email %>
					data-allow-remember-me="false"
          data-name="NBA Tourney Pool"
          data-label="Pay $75.00"
          data-amount="7500"></script>
</div>
<div class="clear_right">
</div>
<% end %>
</li>

</ul>