config/routes.rb
Ncaa::Application.routes.draw do
  get "charges/increase_pool_size"
  post "charges/pay_for_increase" => "charges#pay_for_increase", as: :charges_pay_for_increase
  get "cutoff_date/edit" => "cutoff_date#edit", as: :cutoff_date_edit
  put "cutoff_date/update" => "cutoff_date#update", as: :cutoff_date_update
  put "brackets/update_master" => "brackets#update_master", as: :brackets_update_master
  get "accountsettings/show"
  get "accountsettings/group_welcome"
  get "standings/show"
  get "teams/edit" => "teams#edit", as: :teams_edit
  put "teams/update" => "teams#update", as: :teams_update
  get "brackets/edit" => "brackets#edit", as: :brackets_edit
  get "brackets/:user_id/view" => "brackets#view", as: :brackets_view
  get "brackets/edit_master" => "brackets#edit_master", as: :edit_master_bracket
  get "brackets/view_master" => "brackets#view_master", as: :view_master_bracket
	resources :brackets
	resources :charges
  devise_for :admins, :controllers => { :registrations => :registrations }
  devise_for :players, :controllers => { :registrations => :registrations }
  get "staticpages/index"
  get "howitworks" => "staticpages#howitworks", as: :staticpages_howitworks
  get "scoring" => "staticpages#scoring", as: :staticpages_scoring
  get "pricing" => "staticpages#pricing", as: :staticpages_pricing
  get "contact" => "staticpages#contact", as: :staticpages_contact
  get "staticpages/notauthorized"
  get "staticpages/nopairings"
  get "staticpages/signupthanks"
  get "staticpages/notpaid"
  get "staticpages/overmaxplayers"
  get "staticpages/nomoresignups"

  get "testpages/test"

  root 'staticpages#index'

  

end

app/views/layouts/_brand_with_year.erb
2014 NBA Playoff Pool

app/views/layouts/_navbar_admin_logged_in.html.erb
    <!-- Fixed navbar -->
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
						<a class="navbar-brand" href="/brackets/<%= current_admin.id %>/edit"><%=render "/layouts/brand_with_year"%></a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
        		<li class="<%= 'active' if current_page?(brackets_edit_path) %>"><%= link_to "My Bracket", brackets_edit_path %></li>


            <li class="<%= 'active' if current_page?(standings_show_path) %>"><%= link_to "Standings", standings_show_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account<b class="caret"></b></a>
              <ul class="dropdown-menu">
								<li><%= link_to "Settings", edit_admin_registration_path %></li>
								<li><%= link_to "Pool Info", charges_increase_pool_size_path %></li>
								<li><%= link_to "Sign Out", destroy_admin_session_path,  :method => :delete %></li>
                <% if current_admin.email == "garthmcgraw@statgolf.com" %>
								<li class="divider"></li>
                <li><%= link_to "Master Bracket", edit_master_bracket_path %></li>
                <li><%= link_to "Edit Teams", teams_edit_path %></li>
                <li><%= link_to "Edit Cutoff Date", cutoff_date_edit_path %></li>
                <% end %>
              </ul>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

app/views/layouts/_navbar_not_logged_in.html.erb
    <!-- Fixed navbar -->
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/"><%=render "/layouts/brand_with_year"%></a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
	  <li class="<%= 'active' if current_page?(staticpages_howitworks_path) %>"><%= link_to "How it Works", staticpages_howitworks_path %></li>
	  <li class="<%= 'active' if current_page?(staticpages_pricing_path) %>"><%= link_to "Pricing", staticpages_pricing_path %></li>
	  <li class="<%= 'active' if current_page?(staticpages_scoring_path) %>"><%= link_to "Scoring", staticpages_scoring_path %></li>
	  <li class="<%= 'active' if current_page?(staticpages_contact_path) %>"><%= link_to "Contact", staticpages_contact_path %></li>
	  <li class="<%= 'active' if current_page?(new_player_session_path) %>"><%= link_to "Sign in", new_player_session_path %></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

app/views/layouts/_navbar_player_logged_in.html.erb
    <!-- Fixed navbar -->
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
						<a class="navbar-brand" href="/brackets/<%= current_player.id %>/edit"><%=render "/layouts/brand_with_year"%></a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
        		<li class="<%= 'active' if current_page?(brackets_edit_path) %>"><%= link_to "My Bracket", brackets_edit_path %></li>


            <li class="<%= 'active' if current_page?(standings_show_path) %>"><%= link_to "Standings", standings_show_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account<b class="caret"></b></a>
              <ul class="dropdown-menu">
								<li><%= link_to "Settings", edit_player_registration_path %></li>
								<li><%= link_to "Pool Info", charges_increase_pool_size_path %></li>
								<li><%= link_to "Sign Out", destroy_player_session_path,  :method => :delete %></li>
								<% if current_player.email == "garthmcgraw@statgolf.com" %>
								<li class="divider"></li>
								<li><%= link_to "Master Bracket", edit_master_bracket_path %></li>
								<li><%= link_to "Edit Teams", teams_edit_path %></li>
								<li><%= link_to "Edit Cutoff Date", cutoff_date_edit_path %></li>
								<% end %>
              </ul>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NBA Playoff Pool - <%= yield :title %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body role="document">


<%=
		if ( player_signed_in? )
      render "/layouts/navbar_player_logged_in"
    elsif ( admin_signed_in? )
      render "/layouts/navbar_admin_logged_in"
		else
      render "/layouts/navbar_not_logged_in"
    end
%>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>




    <div class="container theme-showcase" role="main">
    	<div class="jumbotron"> 
		  		<%= yield %>
			</div>
		</div>
</body>
    <div id="footer">
      <div class="footer_content float_left text-muted">
        &copy; <%= Time.now.year %> <a href="http://www.playoffpoolz.com">PlayoffPoolz.com</a> all rights reserved.
      </div>
      <div class="footer_content float_right text-muted">
        Contact us at <a href="mailto:support@playoffpoolz.com">support@playoffpoolz.com</a>
      </div>
    </div>
</html>

app/views/layouts/brackets.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>NBA Playoff Pool - <%= yield :title %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body role="document">


<%=
		if ( player_signed_in? )
      render "/layouts/navbar_player_logged_in"
    elsif ( admin_signed_in? )
      render "/layouts/navbar_admin_logged_in"
		else
      render "/layouts/navbar_not_logged_in"
    end
%>


<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

</div>
    <div id="bracket_container"> 
		  	<%= yield %>
		</div>
</body>
    <div id="footer">
      <div class="footer_content float_left text-muted">
        &copy; <%= Time.now.year %> <a href="http://www.playoffpoolz.com">PlayoffPoolz.com</a> all rights reserved.
      </div>
      <div class="footer_content float_right text-muted">
        Contact us at <a href="mailto:support@playoffpoolz.com">support@playoffpoolz.com</a>
      </div>
    </div>
</html>

app/views/layouts/old_charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <%= yield %>
</body>
</html>